### PR TITLE
Fix function names without package prefix

### PR DESCRIPTION
**Pull request by xuchunyang**
For #13.

A github workflow is also added to run the byte compile & tests, so we can ensure the PR does not break the existing code. Lexical binding is also enabled by the way #14.

### CODE REVIEW

**Comment by xuchunyang** [comment]
> A github workflow is also added to run the byte compile & tests, so we can ensure the PR does not break the existing code

It runs successfully according to https://github.com/xuchunyang/emacs-web-server/actions?query=workflow%3ACI

I have also tested the new code with a simple web app, and the result is good.

**Comment by xuchunyang** [comment]
I just notice this package is on gnu elpa as well. I should mention that I've signed the fsf copyright assignment for the gnu emacs project.

**Comment by xuchunyang** [comment]
Closing as you've fixed the issue.

**Comment by eschulte** [comment]
Sorry, I didn't notice this before I pushed my change.  Is there anything in this PR which should be included?  It looks like you did some good CI/testing work as well.

**Comment by eschulte** [comment]
Okay, I've brought in your CI changes from this PR into the master branch.  This is great, Thanks!

**Pull request closed without merging**
